apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus
  template:
    metadata:
      labels:
        app: java-quarkus
    spec:
      containers:
      - name: java-quarkus
        image: quay.io/pratik10596/java-quarkus
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-quarkus
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: java-quarkus
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: java-quarkus
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: java-quarkus.${HOST_NAME}
    http:
      paths:
      - backend:
          serviceName: java-quarkus
          servicePort: 8080
        path: /
